eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 5
    service-url:
      default-zone: http://localhost:8761/eureka
      
server:
  port: 8763
  
service:
  welcome:
    message: Hello from cloud admin-server
  
spring:
  application:
    name: admin-server
  config:
    import: "optional:configserver:http://localhost:8088"
  output:
    ansi:
      enabled: always
