eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      default-zone: http://localhost:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

resilience4j:
  circuitbreaker:
    instances:
      CircuitBreakerService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
        
server:
  port: 8090

service:
  welcome:
    message: Hello from cloud cloud-rest-client
    
spring:
  application:
    name: cloud-rest-client
  boot:
    admin:
      client:
        url: http://localhost:8763
  config:
    import: "optional:configserver:http://localhost:8088"
